<a href="https://colab.research.google.com/github/youkyung2/dataAnalysis/blob/master/%EC%9E%91%EC%97%85%ED%98%95_%EC%A0%9C1%EC%9C%A0%ED%98%95_%EC%98%88%EC%8B%9C%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

작업형 제 1유형 예시문제

URL : https://www.datamanim.com/dataset/03_dataq/main_p1.html

데이터셋 : https://raw.githubusercontent.com/youkyung2/dataAnalysis/master/dataq/


##### mtcars

In [2]:
import pandas as pd
import matplotlib.pyplot as plt

dataurl = 'https://raw.githubusercontent.com/youkyung2/dataAnalysis/master/dataq/'

In [152]:
df = pd.read_csv(dataurl+'mtcars.csv',index_col=0)
df.head(4)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4       21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag   21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710      22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1
Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3     1

In [154]:
df2 = pd.read_csv(dataurl + 'mtcars.csv',index_col = 0)
df2.head(3)

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
Mazda RX4      21.0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4     4
Datsun 710     22.8    4  108.0   93  3.85  2.320  18.61   1   1     4     1

In [156]:
df.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [ ]:
df.qsec

In [8]:
import sklearn.preprocessing
dir(sklearn.preprocessing)[:10]

['Binarizer',
 'FunctionTransformer',
 'KBinsDiscretizer',
 'KernelCenterer',
 'LabelBinarizer',
 'LabelEncoder',
 'MaxAbsScaler',
 'MinMaxScaler',
 'MultiLabelBinarizer',
 'Normalizer']

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [13]:
sc = MinMaxScaler()

In [33]:
testfit = sc.fit(df.qsec.to_numpy().reshape(-1,1))
testtrans = testfit.transform(df.qsec.to_numpy().reshape(-1,1))
testtrans

array([[0.23333333],
       [0.3       ],
       [0.48928571],
       [0.58809524],
       [0.3       ],
       [0.68095238],
       [0.15952381],
       [0.6547619 ],
       [1.        ],
       [0.45238095],
       [0.52380952],
       [0.3452381 ],
       [0.36904762],
       [0.41666667],
       [0.41428571],
       [0.3952381 ],
       [0.34761905],
       [0.59166667],
       [0.47857143],
       [0.64285714],
       [0.65595238],
       [0.28214286],
       [0.33333333],
       [0.10833333],
       [0.30357143],
       [0.52380952],
       [0.26190476],
       [0.28571429],
       [0.        ],
       [0.11904762],
       [0.01190476],
       [0.48809524]])

In [34]:
sc.fit(df.qsec.to_numpy().reshape(-1,1))
testtrans = sc.transform(df.qsec.to_numpy().reshape(-1,1))
testtrans

array([[0.23333333],
       [0.3       ],
       [0.48928571],
       [0.58809524],
       [0.3       ],
       [0.68095238],
       [0.15952381],
       [0.6547619 ],
       [1.        ],
       [0.45238095],
       [0.52380952],
       [0.3452381 ],
       [0.36904762],
       [0.41666667],
       [0.41428571],
       [0.3952381 ],
       [0.34761905],
       [0.59166667],
       [0.47857143],
       [0.64285714],
       [0.65595238],
       [0.28214286],
       [0.33333333],
       [0.10833333],
       [0.30357143],
       [0.52380952],
       [0.26190476],
       [0.28571429],
       [0.        ],
       [0.11904762],
       [0.01190476],
       [0.48809524]])

In [28]:
test = sc.fit_transform(df.qsec.to_numpy().reshape(-1,1))
test

array([[0.23333333],
       [0.3       ],
       [0.48928571],
       [0.58809524],
       [0.3       ],
       [0.68095238],
       [0.15952381],
       [0.6547619 ],
       [1.        ],
       [0.45238095],
       [0.52380952],
       [0.3452381 ],
       [0.36904762],
       [0.41666667],
       [0.41428571],
       [0.3952381 ],
       [0.34761905],
       [0.59166667],
       [0.47857143],
       [0.64285714],
       [0.65595238],
       [0.28214286],
       [0.33333333],
       [0.10833333],
       [0.30357143],
       [0.52380952],
       [0.26190476],
       [0.28571429],
       [0.        ],
       [0.11904762],
       [0.01190476],
       [0.48809524]])

In [32]:
len(test[test>=0.5])

9

In [23]:
df.qsec.to_numpy().reshape(-1,1)

array([[16.46],
       [17.02],
       [18.61],
       [19.44],
       [17.02],
       [20.22],
       [15.84],
       [20.  ],
       [22.9 ],
       [18.3 ],
       [18.9 ],
       [17.4 ],
       [17.6 ],
       [18.  ],
       [17.98],
       [17.82],
       [17.42],
       [19.47],
       [18.52],
       [19.9 ],
       [20.01],
       [16.87],
       [17.3 ],
       [15.41],
       [17.05],
       [18.9 ],
       [16.7 ],
       [16.9 ],
       [14.5 ],
       [15.5 ],
       [14.6 ],
       [18.6 ]])

###. fit() vs fit_transform()

url : https://www.inflearn.com/questions/19038

In [39]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.metrics import accuracy_score

# 붓꽃 데이터 세트를 로딩합니다.
iris = load_iris()
iris_data = iris.data
iris_label = iris.target

# MinMaxScaler() Scaler객체 생성.
scaler = MinMaxScaler()
# 학습 데이터, 테스트 데이터로 나누기 전에 fit과 transform 으로 변환. fit_transform() 도 무방. 
scaler.fit(iris.data)
scaled_iris_data = scaler.transform(iris.data)

# scale된 iris_data로 학습과 테스트 데이터를 나눔.
X_train, X_test, y_train, y_test = train_test_split(scaled_iris_data, iris_label,
                                                    test_size=0.2, random_state=2)

lr = LogisticRegression()
lr.fit(X_train, y_train)
pred = lr.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


In [157]:
mtcars = pd.read_csv(dataurl+'mtcars.csv',index_col=0)

In [41]:
qsec = mtcars.qsec.to_numpy().reshape(-1,1)

In [46]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
sc.fit(qsec)
transed = sc.transform(qsec)
sum(transed>=0.5)

array([9])

In [48]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(mtcars.qsec.to_numpy().reshape(-1,1))
res = sc.transform(mtcars.qsec.to_numpy().reshape(-1,1))
Max = max(res)
Min = min(res)
print(Max, Min)

[2.87198554] [-1.90399635]


In [49]:
sc2 = StandardScaler()
res = sc2.fit_transform(mtcars.qsec.to_numpy().reshape(-1,1))
Max = max(res)
Min = min(res)
print(Max, Min)

[2.87198554] [-1.90399635]


In [50]:
import numpy as np

In [51]:
wt = mtcars.wt
wt

Mazda RX4              2.620
Mazda RX4 Wag          2.875
Datsun 710             2.320
Hornet 4 Drive         3.215
Hornet Sportabout      3.440
Valiant                3.460
Duster 360             3.570
Merc 240D              3.190
Merc 230               3.150
Merc 280               3.440
Merc 280C              3.440
Merc 450SE             4.070
Merc 450SL             3.730
Merc 450SLC            3.780
Cadillac Fleetwood     5.250
Lincoln Continental    5.424
Chrysler Imperial      5.345
Fiat 128               2.200
Honda Civic            1.615
Toyota Corolla         1.835
Toyota Corona          2.465
Dodge Challenger       3.520
AMC Javelin            3.435
Camaro Z28             3.840
Pontiac Firebird       3.845
Fiat X1-9              1.935
Porsche 914-2          2.140
Lotus Europa           1.513
Ford Pantera L         3.170
Ferrari Dino           2.770
Maserati Bora          3.570
Volvo 142E             2.780
Name: wt, dtype: float64

In [56]:
IQR = wt.quantile(0.75) - wt.quantile(0.25)

In [57]:
minimun = wt.quantile(0.25) - 1.5 * IQR
maximun = wt.quantile(0.75) + 1.5 * IQR
print(minimun, maximun)

1.0381249999999997 5.153125


In [64]:
wt[(wt < minimun) | (wt > maximun)].values

array([5.25 , 5.424, 5.345])

In [84]:
mtcars.corr()['mpg'][1:].to_frame().sort_values('mpg',ascending=False)

mpg
drat  0.681172
vs    0.664039
am    0.599832
gear  0.480285
qsec  0.418684
carb -0.550925
hp   -0.776168
disp -0.847551
cyl  -0.852162
wt   -0.867659

In [91]:
q5 = mtcars.iloc[:,1:]
# mtcars.drop('mpg',axis = 1)

In [93]:
q5.columns

Index(['cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb'], dtype='object')

In [96]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

pcaDf = sc.fit_transform(q5)

In [98]:
from sklearn.decomposition import PCA

componentsNum=10
pca = PCA(n_components=componentsNum) 
printcipalComponents = pca.fit_transform(pcaDf)
principalDf = pd.DataFrame(data=printcipalComponents, columns = ['component'+str(x) for x in range(componentsNum)])

componentDf = pd.DataFrame(pca.explained_variance_ratio_,columns=['cumsumVariance']).cumsum().reset_index()
componentDf['index'] +=1
componentDf=componentDf.rename(columns={'index':'componentsCount'})

In [99]:
componentDf

componentsCount  cumsumVariance
0                1        0.576022
1                2        0.840986
2                3        0.900708
3                4        0.927658
4                5        0.949883
5                6        0.970895
6                7        0.984187
7                8        0.992255
8                9        0.997620
9               10        1.000000

In [159]:
mtcars.index

Index(['Mazda RX4', 'Mazda RX4 Wag', 'Datsun 710', 'Hornet 4 Drive',
       'Hornet Sportabout', 'Valiant', 'Duster 360', 'Merc 240D', 'Merc 230',
       'Merc 280', 'Merc 280C', 'Merc 450SE', 'Merc 450SL', 'Merc 450SLC',
       'Cadillac Fleetwood', 'Lincoln Continental', 'Chrysler Imperial',
       'Fiat 128', 'Honda Civic', 'Toyota Corolla', 'Toyota Corona',
       'Dodge Challenger', 'AMC Javelin', 'Camaro Z28', 'Pontiac Firebird',
       'Fiat X1-9', 'Porsche 914-2', 'Lotus Europa', 'Ford Pantera L',
       'Ferrari Dino', 'Maserati Bora', 'Volvo 142E'],
      dtype='object')

In [114]:
test = mtcars.reset_index()
test['index'].isnull().sum()
test['index'][0].split(' ')[0]

'Mazda'

In [158]:
pd.DataFrame(list(mtcars.index.str.split(' ')))[0].values

array(['Mazda', 'Mazda', 'Datsun', 'Hornet', 'Hornet', 'Valiant',
       'Duster', 'Merc', 'Merc', 'Merc', 'Merc', 'Merc', 'Merc', 'Merc',
       'Cadillac', 'Lincoln', 'Chrysler', 'Fiat', 'Honda', 'Toyota',
       'Toyota', 'Dodge', 'AMC', 'Camaro', 'Pontiac', 'Fiat', 'Porsche',
       'Lotus', 'Ford', 'Ferrari', 'Maserati', 'Volvo'], dtype=object)

In [133]:
mtcars['brand'] = pd.DataFrame(list(mtcars.index.str.split(' ')))[0].values

In [188]:
mtcars['brand'] = pd.DataFrame(test['index'].apply(lambda x : x.split(' ')[0]))['index'].values
mtcars['brand']

Mazda RX4                 Mazda
Mazda RX4 Wag             Mazda
Datsun 710               Datsun
Hornet 4 Drive           Hornet
Hornet Sportabout        Hornet
Valiant                 Valiant
Duster 360               Duster
Merc 240D                  Merc
Merc 230                   Merc
Merc 280                   Merc
Merc 280C                  Merc
Merc 450SE                 Merc
Merc 450SL                 Merc
Merc 450SLC                Merc
Cadillac Fleetwood     Cadillac
Lincoln Continental     Lincoln
Chrysler Imperial      Chrysler
Fiat 128                   Fiat
Honda Civic               Honda
Toyota Corolla           Toyota
Toyota Corona            Toyota
Dodge Challenger          Dodge
AMC Javelin                 AMC
Camaro Z28               Camaro
Pontiac Firebird        Pontiac
Fiat X1-9                  Fiat
Porsche 914-2           Porsche
Lotus Europa              Lotus
Ford Pantera L             Ford
Ferrari Dino            Ferrari
Maserati Bora          Maserati
Volvo 14

In [182]:
mtcars['brand'] = pd.DataFrame(test['index'].apply(lambda x : x.split(' ')[0]))
mtcars['brand']

Mazda RX4              NaN
Mazda RX4 Wag          NaN
Datsun 710             NaN
Hornet 4 Drive         NaN
Hornet Sportabout      NaN
Valiant                NaN
Duster 360             NaN
Merc 240D              NaN
Merc 230               NaN
Merc 280               NaN
Merc 280C              NaN
Merc 450SE             NaN
Merc 450SL             NaN
Merc 450SLC            NaN
Cadillac Fleetwood     NaN
Lincoln Continental    NaN
Chrysler Imperial      NaN
Fiat 128               NaN
Honda Civic            NaN
Toyota Corolla         NaN
Toyota Corona          NaN
Dodge Challenger       NaN
AMC Javelin            NaN
Camaro Z28             NaN
Pontiac Firebird       NaN
Fiat X1-9              NaN
Porsche 914-2          NaN
Lotus Europa           NaN
Ford Pantera L         NaN
Ferrari Dino           NaN
Maserati Bora          NaN
Volvo 142E             NaN
Name: brand, dtype: object

In [175]:
test['index']

0               Mazda RX4
1           Mazda RX4 Wag
2              Datsun 710
3          Hornet 4 Drive
4       Hornet Sportabout
5                 Valiant
6              Duster 360
7               Merc 240D
8                Merc 230
9                Merc 280
10              Merc 280C
11             Merc 450SE
12             Merc 450SL
13            Merc 450SLC
14     Cadillac Fleetwood
15    Lincoln Continental
16      Chrysler Imperial
17               Fiat 128
18            Honda Civic
19         Toyota Corolla
20          Toyota Corona
21       Dodge Challenger
22            AMC Javelin
23             Camaro Z28
24       Pontiac Firebird
25              Fiat X1-9
26          Porsche 914-2
27           Lotus Europa
28         Ford Pantera L
29           Ferrari Dino
30          Maserati Bora
31             Volvo 142E
Name: index, dtype: object

In [166]:
mtcars['brand'] = test['index'].apply(lambda x : x.split(' ')[0]).to_frame().values.reshape(1,32)

ValueError: ignored

In [119]:
len(mtcars)

32

In [173]:
mtcars.head(3)

mpg  cyl   disp   hp  drat  ...  vs  am  gear  carb  brand
Mazda RX4      21.0    6  160.0  110  3.90  ...   0   1     4     4    NaN
Mazda RX4 Wag  21.0    6  160.0  110  3.90  ...   0   1     4     4    NaN
Datsun 710     22.8    4  108.0   93  3.85  ...   1   1     4     1    NaN

[3 rows x 12 columns]

In [123]:
mtcars.index.str

##### diamond

In [190]:
import pandas as pd

df = pd.read_csv(dataurl + 'diamonds.csv',index_col=0)
df.head(3)

carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [196]:
df[['carat','price']].corr()

carat     price
carat  1.000000  0.921591
price  0.921591  1.000000

In [201]:
df[['carat','price']].corr().iloc[0,1]

0.9215913011935697

In [202]:
from scipy import stats
corr_by_scipy , pv = stats.pearsonr(df['carat'],df['price'])
print(corr_by_scipy)
print(pv)

0.9215913011934764
0.0


In [203]:
H_prop = df[df['color'] == 'H']
static, pv = stats.ttest_1samp(H_prop['price'], 3932)

if pv<0.05 :
  hypo = False
else :
  hypo = True

In [204]:
print(static)
print(pv)
print(hypo)

11.988997411117696
7.569973305218302e-33
False


In [206]:
H_prop['price'].mean()

4486.669195568401

In [207]:
F = df[df['color'] == 'F']
G = df[df['color'] == 'G']

leve = stats.levene(F['price'], G['price'])
fli = stats.fligner(F['price'], G['price'])
bartlet = stats.bartlett(F['price'], G['price'])

print(leve)
print(fli)
print(bartlet)

# 등분산조건 확인 :
# 귀무가설기각 ( F, G 집단 간 분산 같지 않다.)

LeveneResult(statistic=53.627886257416655, pvalue=2.511093007074788e-13)
FlignerResult(statistic=37.04347553879807, pvalue=1.155244880009172e-09)
BartlettResult(statistic=47.52732212008511, pvalue=5.424264079418252e-12)


In [209]:
t_test_FG = stats.ttest_ind(G['price'],F['price'],equal_var = False)
t_test_FG

# 독립표본 t 검정 시행 :
# 귀무가설기각 (F, G 집단간 평균 같지 않다.)

Ttest_indResult(statistic=5.045279980436125, pvalue=4.5670321227041464e-07)

In [210]:
D = df[df['color'] == 'D']

leve2 = stats.levene(F['price'], D['price'], G['price'])
fli2 = stats.fligner(F['price'], D['price'], G['price'])
bartlet2 = stats.bartlett(F['price'], D['price'], G['price'])

print(leve2)
print(fli2)
print(bartlet2)

LeveneResult(statistic=118.97521469312785, pvalue=3.557425577381817e-52)
FlignerResult(statistic=494.64591695585733, pvalue=3.881538382653518e-108)
BartlettResult(statistic=289.14364432535103, pvalue=1.634012581050329e-63)


In [211]:
anova = stats.f_oneway(F['price'], D['price'], G['price'])
anova

# anova 검정을 실행하였을 때,
# 세 집단 중 어느 두 집단의 평균은 같지 않다.

F_onewayResult(statistic=101.1811790316069, pvalue=1.6513790091285713e-44)

In [212]:
df.head(3)

carat      cut color clarity  depth  table  price     x     y     z
1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [218]:
df2 = df[['carat','depth','table','price','x','y','z']]
df2

carat  depth  table  price     x     y     z
1       0.23   61.5   55.0    326  3.95  3.98  2.43
2       0.21   59.8   61.0    326  3.89  3.84  2.31
3       0.23   56.9   65.0    327  4.05  4.07  2.31
4       0.29   62.4   58.0    334  4.20  4.23  2.63
5       0.31   63.3   58.0    335  4.34  4.35  2.75
...      ...    ...    ...    ...   ...   ...   ...
53936   0.72   60.8   57.0   2757  5.75  5.76  3.50
53937   0.72   63.1   55.0   2757  5.69  5.75  3.61
53938   0.70   62.8   60.0   2757  5.66  5.68  3.56
53939   0.86   61.0   58.0   2757  6.15  6.12  3.74
53940   0.75   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 7 columns]

In [219]:
IQR = df2.quantile(0.75) - df2.quantile(0.25)

minimun = df2.quantile(0.25) - (1.5*IQR)
maximun = df2.quantile(0.75) + (1.5*IQR)

print(minimun, maximun)

carat      -0.560
depth      58.750
table      51.500
price   -5611.375
x           1.965
y           1.990
z           1.215
dtype: float64 carat        2.000
depth       64.750
table       63.500
price    11885.625
x            9.285
y            9.270
z            5.735
dtype: float64


In [231]:
data = df2[(df2 <= minimun) | (df2 > maximun)].count()
data

carat    1889
depth    2545
table     605
price    3540
x          32
y          29
z          49
dtype: int64

In [250]:
data.values

array([1889, 2545,  605, 3540,   32,   29,   49])

In [235]:
data.index

Index(['carat', 'depth', 'table', 'price', 'x', 'y', 'z'], dtype='object')

In [249]:
ratio_df = pd.DataFrame(data.reset_index()).rename(columns = {
    'index' : 'column',
    '0' : 'ratio'
}, inplace = True)
ratio_df

In [252]:
df3 = pd.DataFrame(data.reset_index())
df3

index     0
0  carat  1889
1  depth  2545
2  table   605
3  price  3540
4      x    32
5      y    29
6      z    49

In [257]:
df3.columns = ['column','ratio']
df3.columns

ratio_df = df3

In [259]:
ratio_df.sort_values('ratio',ascending=False)

column  ratio
3  price   3540
1  depth   2545
0  carat   1889
2  table    605
6      z     49
4      x     32
5      y     29

In [261]:
df.groupby(['color']).price.agg(['max','min','mean'])

max  min         mean
color                         
D      18693  357  3169.954096
E      18731  326  3076.752475
F      18791  342  3724.886397
G      18818  354  3999.135671
H      18803  337  4486.669196
I      18823  334  5091.874954
J      18710  335  5323.818020

In [263]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
result = le.fit_transform(df['color'])
print(result)

[1 1 1 ... 0 4 0]


In [266]:
df['colorLabel'] = result
df['colorLabel'].head(3)

df['colorLabel'].value_counts()

3    11292
1     9797
2     9542
4     8304
0     6775
5     5422
6     2808
Name: colorLabel, dtype: int64

In [267]:
df.groupby('cut').colorLabel.mean()

cut
Fair         2.851553
Good         2.573176
Ideal        2.529256
Premium      2.697339
Very Good    2.566545
Name: colorLabel, dtype: float64

In [268]:
df['price']

1         326
2         326
3         327
4         334
5         335
         ... 
53936    2757
53937    2757
53938    2757
53939    2757
53940    2757
Name: price, Length: 53940, dtype: int64

In [276]:
int(326/1000)
int(1002/1000)
int(2034/1000)

2

In [281]:
int((1000-1)/1000)

0

In [277]:
df['priceLabel'] = df.price.apply(lambda x : int(x/1000))
df['priceLabel']

1        0
2        0
3        0
4        0
5        0
        ..
53936    2
53937    2
53938    2
53939    2
53940    2
Name: priceLabel, Length: 53940, dtype: int64

In [278]:
df.priceLabel.value_counts()

0     14499
1      9704
2      6131
4      4653
3      4226
5      3174
6      2278
7      1669
8      1307
9      1076
10      935
11      824
12      702
13      603
15      514
14      503
16      424
17      406
18      312
Name: priceLabel, dtype: int64

비디오게임 판매량 및 등급

In [285]:
import pandas as pd
df = pd.read_csv(dataurl + 'video_games_sale.csv',index_col=0)
df.head(2)

Name Platform  Year_of_Release  ... Developer Rating  Year_of_ten
0      Wii Sports      Wii           2006.0  ...  Nintendo      E       2000.0
1  Mario Kart Wii      Wii           2008.0  ...  Nintendo      E       2000.0

[2 rows x 17 columns]

In [287]:
import datetime

In [289]:
df.describe()

Year_of_Release     NA_Sales  ...    User_Count  Year_of_ten
count      6825.000000  6825.000000  ...   6825.000000  6825.000000
mean       2007.436777     0.394484  ...    174.722344  2003.012454
std           4.211248     0.967385  ...    587.428538     4.846167
min        1985.000000     0.000000  ...      4.000000  1980.000000
25%        2004.000000     0.060000  ...     11.000000  2000.000000
50%        2007.000000     0.150000  ...     27.000000  2000.000000
75%        2011.000000     0.390000  ...     89.000000  2010.000000
max        2016.000000    41.360000  ...  10665.000000  2010.000000

[8 rows x 11 columns]

In [304]:
int(str(int(2009 / 10)) + '0')

2000

In [305]:
df['year_of_ten'] = df.Year_of_Release.apply(lambda x : int(str(int(x / 10)) + '0'))
df['year_of_ten']

0       2000
1       2000
2       2000
3       2000
4       2000
        ... 
6820    2000
6821    2000
6822    2010
6823    2010
6824    2010
Name: year_of_ten, Length: 6825, dtype: int64

In [306]:
df['year_of_ten'].value_counts()

2000    4609
2010    2137
1990      77
1980       2
Name: year_of_ten, dtype: int64

In [315]:
len(df[(df.Platform.isin(['PS','PS2','PS3','PS4','PSV'])) & (df.Genre == 'Action')])

616

In [341]:
df[df.Platform.isin(plat400)].groupby('Platform',as_index=False).User_Score.mean().sort_values('User_Score',ascending=False)

Platform  User_Score
2      PS2    7.664386
6       XB    7.540708
1       PC    7.060369
0       DS    7.047198
4      Wii    6.903758
3      PS3    6.782705
5     X360    6.780769

In [329]:
plat400 = list(['PS2','X360','PS3','PC','XB','Wii','DS'])
plat400

['PS2', 'X360', 'PS3', 'PC', 'XB', 'Wii', 'DS']

In [323]:
df.Platform.value_counts() >= 400

PS2      True
X360     True
PS3      True
PC       True
XB       True
Wii      True
DS       True
PSP     False
GC      False
PS4     False
GBA     False
XOne    False
3DS     False
PS      False
PSV     False
WiiU    False
DC      False
Name: Platform, dtype: bool

In [322]:
df.iloc[0:5]

Name Platform  ...  Year_of_ten year_of_ten
0             Wii Sports      Wii  ...       2000.0        2000
1         Mario Kart Wii      Wii  ...       2000.0        2000
2      Wii Sports Resort      Wii  ...       2000.0        2000
3  New Super Mario Bros.       DS  ...       2000.0        2000
4               Wii Play      Wii  ...       2000.0        2000

[5 rows x 18 columns]

In [345]:
df[df.Name.str.contains('Mario')]['Developer'].value_counts() == 3

Nintendo                                                        False
Hudson                                                          False
Camelot Software Planning                                       False
Intelligent Systems                                             False
Nintendo, Nd Cube                                                True
Nintendo, Nintendo Software Technology                           True
Next Level Games                                                False
Square Enix                                                     False
Hudson Soft                                                     False
Nintendo, Camelot Software Planning                             False
Fuse Games Limited                                              False
Nintendo EAD Tokyo                                              False
Retro Studios, Entertainment Analysis & Development Division    False
Nd Cube                                                         False
Namco Bandai Games  

In [347]:
df[df.Platform == 'PS2'].User_Score.kurtosis()

2.4920035946875965

In [351]:
((df['NA_Sales'] + df['EU_Sales'] + df['JP_Sales'] + df['Other_Sales']) != df['Global_Sales']).sum()

3636

In [354]:
sum((df['User_Count'] >= 120) & (df['User_Score'] >= 9))

86

In [356]:
from sklearn.preprocessing import RobustScaler

rb= RobustScaler()
rb_fit = rb.fit_transform(df.Global_Sales.values.reshape(-1,1))
len(rb_fit[rb_fit > 40])

6